package com.winter.controller;

public class Human {//you can have multiple files with the same name in your project but only in different packages...
					//As you noticed, we have 3 Human classes in our project...

}
