
public class Human {//This file does not belong to any package that is why I do not see any package statement at the top...
	//you can have multiple files with the same name in your project but only in different packages...
	//As you noticed, we have 3 Human classes in our project...


}
